/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecteur;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.itextpdf.text.pdf.pdfcleanup.PdfCleanUpLocation;
import com.itextpdf.text.pdf.pdfcleanup.PdfCleanUpProcessor;
 
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;



/**
 *
 * @author tbalandier
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    
    private final DocPDF doc;
    
    public Interface() {
        initComponents();
        this.doc = new DocPDF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_fichier = new javax.swing.JLabel();
        button_parcourir = new javax.swing.JButton();
        button_lire = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_form = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_fichier.setText("Nom du fichier");
        lb_fichier.setToolTipText("");
        lb_fichier.setName("lb_fichier"); // NOI18N

        button_parcourir.setLabel("Parcourir...");
        button_parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_parcourirActionPerformed(evt);
            }
        });

        button_lire.setText("Lire");
        button_lire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lireActionPerformed(evt);
            }
        });

        text_form.setEditable(false);
        text_form.setColumns(20);
        text_form.setRows(5);
        jScrollPane1.setViewportView(text_form);
        text_form.getAccessibleContext().setAccessibleName("text_form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_lire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_fichier)
                        .addComponent(button_parcourir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addComponent(lb_fichier)
                        .addGap(18, 18, 18)
                        .addComponent(button_parcourir)
                        .addGap(76, 76, 76)
                        .addComponent(button_lire, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        lb_fichier.getAccessibleContext().setAccessibleName("lb_ficher");
        button_parcourir.getAccessibleContext().setAccessibleName("button_parcourir");
        button_lire.getAccessibleContext().setAccessibleName("button_lire");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_parcourirActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "PDF Documents", "pdf");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            this.doc.setNom(chooser.getSelectedFile().getName());
            this.doc.setChemin(chooser.getSelectedFile().getPath());

            this.lb_fichier.setText(doc.getNom());

            //test affichage
            this.doc.show();
        }
    }//GEN-LAST:event_button_parcourirActionPerformed

    private void button_lireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lireActionPerformed
        // TODO add your handling code here:
        String text = "";
        try {
            //this.doc.show();
            text = ReadPDF(this.doc.getChemin());
        } catch (IOException | DocumentException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(text.equals("")){
            this.lb_fichier.setText("Nom du fichier.");
            this.text_form.setText("");
        }
        else {
            this.text_form.setText(text);
        }
    }//GEN-LAST:event_button_lireActionPerformed

    public void createPdf(String filename)
	throws DocumentException, IOException {
        // step 1
        Document document = new Document();
        // step 2
        PdfWriter.getInstance(document, new FileOutputStream(filename));
        // step 3
        document.open();
        // step 4
        document.add(new Paragraph("Hello World!"));
        document.add(new Paragraph("Hello Me"));
        // step 5
        document.close();
    }
    
    private static String ReadPDF(String pdf_url) throws IOException, DocumentException
    {
        ArrayList<Rubrique> tabRubriqueBilanTotal = new ArrayList<>();
        Rubrique rubrique;
        StringBuilder str = new StringBuilder();

        pdf_url = "C:\\Users\\Super_t0t0\\Documents\\GitHub\\ReaderPDF\\ressources\\sample-6.pdf";
        PdfReader original_reader = new PdfReader(pdf_url);

        //OK pour la découpe du pdf
        //TODO
        //FAIRE UNE DECOUPE SPE PAR TYPE DE PAGE
        // FAIRE TEST JE PENSE
        // UNE FOIS FINI
        //CLOSE PDF
        for (int page = 1; page <= original_reader.getNumberOfPages(); page++) {
            List<Rectangle> rectangles = new ArrayList<>();
            Rectangle rect1 = new Rectangle(200, 50, 300, 730);
            Rectangle rect2 = new Rectangle(305, 35, 405, 715);
            Rectangle rect3 = new Rectangle(485, 30, 590, 46);
            rectangles.add(rect1);
            rectangles.add(rect2);
            rectangles.add(rect3);
            
            
            
            for (int numrect = 0; numrect < rectangles.size(); numrect++) {
                PdfReader reader = new PdfReader(original_reader);
                System.out.println("TRAITEMENT POUR RECTANGLE=" + numrect);
                String txt = "C:\\Users\\Super_t0t0\\Documents\\GitHub\\ReaderPDF\\ressources\\sample-" + page + numrect + ".pdf";
                File file = new File(txt);
                file.getParentFile().mkdirs();
                //POSE PB
                //com.itextpdf.text.DocumentException: The original document was reused. Read it again from file.
                PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(txt));
                Rectangle rect = rectangles.get(numrect);

                List<PdfCleanUpLocation> cleanUpLocations = new ArrayList<>();

                //TODO
                //Faire une liste de rect par page afin que ca soit auto
                //Rectangle(int x, int y, int width, int height)
                //NE PAS SUPPR Rectangle rect = new Rectangle(200, 50, 300, 730);
                //NE PAS SUPPR Rectangle rect = new Rectangle(305, 35, 405, 715);
                //Rectangle rect = new Rectangle(485, 30, 590, 46);
                //System.out.println("BOTTOM=" + rect.getBottom());
                //System.out.println("TOP=" + rect.getTop());
                //System.out.println("LEFT=" + rect.getLeft());
                //System.out.println("RIGHT=" + rect.getRight());
                
                //PROCEDURE DECOUPE

                cleanUpLocations.add(new PdfCleanUpLocation(page, new Rectangle(0, 0, reader.getPageSize(1).getRight(), rect.getBottom()), BaseColor.GRAY));
                cleanUpLocations.add(new PdfCleanUpLocation(page, new Rectangle(0, 0, rect.getLeft(), reader.getPageSize(1).getTop()), BaseColor.BLUE));
                cleanUpLocations.add(new PdfCleanUpLocation(page, new Rectangle(rect.getRight(), 0, reader.getPageSize(1).getRight(), reader.getPageSize(1).getTop()), BaseColor.YELLOW));
                cleanUpLocations.add(new PdfCleanUpLocation(page, new Rectangle(0, rect.getTop(), reader.getPageSize(1).getRight(), reader.getPageSize(1).getTop()-50+730), BaseColor.CYAN));

                PdfCleanUpProcessor cleaner = new PdfCleanUpProcessor(cleanUpLocations, stamper);
                cleaner.cleanUp();
                stamper.close();
                reader.close();

                System.out.println("FIN CREATION DOC####");
                System.out.println("DEBUT DE LA LECTURE####");

                String pdf_url_temp = "C:\\Users\\Super_t0t0\\Documents\\GitHub\\ReaderPDF\\ressources\\sample-" + page + numrect + ".pdf";             
                PdfReader reader1 = new PdfReader(pdf_url_temp);

                //Patterns de recherche des résultats pour les bilans
                String pattern_vide = "[0-9][A-Z]|[A-Z]{2}";
                String pattern_double = "[A-Z]{2} +[0-9]* [0-9]+";
                String pattern_double_num = "[0-9][A-Z] +[0-9]* [0-9]+";
                List<String>patterns = new ArrayList();

                patterns.add(pattern_vide);
                patterns.add(pattern_double);
                patterns.add(pattern_double_num);

                //Recherche page BILAN - ACTIF
                //Recherche page BILAN - PASSIF
                //Recherche page 
                //pour chaque page, lire ligne.
                //for(int i=22;i<=22;i++) {
                for(int j=1;j<=reader1.getNumberOfPages();j++) {          
                    String text_extract=PdfTextExtractor.getTextFromPage(reader1, j);
                    //System.out.println("EXTRACT PDF = \n" + text_extract);
                    //Appel fonction split chaque ligne du text extrait.
                    String [] lignes = splitPage(text_extract);
                    System.out.println("FIN EXTRACT PDF ###");
                    System.out.println("NB DE LIGNE A TRAITER = " + lignes.length);

                    for (String ligne : lignes) {
                        // EXTACT DES RUBRIQUE PAR VALEUR + TEXT
                        rubrique = recherchebilan(ligne, patterns);
                        if (rubrique.getNom() != null)
                            tabRubriqueBilanTotal.add(rubrique);
                        else
                            System.err.println("UNE RUBRIQUE NON TROUVEE");
                    }
                    System.out.println("NB RUBRIQUE TOTALE POUR RECTANGLE N°" + numrect + " = " + tabRubriqueBilanTotal.size());       
                }
                System.out.println("CLOSE PDF TEMP");
                reader1.close();
            }
        }
        System.out.println("CLOSE PDF");
        original_reader.close();
        
        
        return String.format("%s", str);
    }
    
    //stock chaque ligne dans un tableau de str.
    private static String[] splitPage(String page) {
        
        String[] row = page.split("(?m)\n");
        //row = page.split("(?m)^.*$");
        
        return row;
    }

    private static Rubrique recherchebilan(String ligne, List<String> patterns) {  
        
        Rubrique bil = new Rubrique();
        String resultat;  
        
        for (int i = 0; i < patterns.size(); i++) {            
            Pattern p = Pattern.compile(patterns.get(i));
            Matcher m = p.matcher(ligne);
            if (m.find()) {
                //Créatoin d'une nouvelle rubrique
                resultat = ligne.substring(m.start(), m.end());            
                //SET rubrique du resultat                        
                bil.setNom(getRubriqueRegex(resultat));
                    
                //SET valeur du resultat
                bil.setValeur(getValeurRegex(ligne));

                break;
            }
        }
        //bil.show();
        return bil;
    }

    private static Integer getValeurRegex(String resultat) {
        Integer res;
        String pattern;
        
        pattern = " +[0-9]* [0-9]+";
        
        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(resultat);
        if(m.find()) {
            String str;
            str = (resultat.substring(m.start(), m.end()));
            String replaceAll = str.replaceAll(" ", "");
            res = Integer.parseInt(replaceAll);
        }
        else {
            //System.err.println("VALEUR NON TROUVEE");
            res =0;
        }
        return res;
    }

    private static String getRubriqueRegex(String resultat) {
        String res = null;
        String pattern;
        
        pattern = "[0-9][A-Z]|[A-Z]{2}";
        
        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(resultat);

        if(m.find()) {
            res = (resultat.substring(m.start(), m.end()));
        }
        return res;
    }

    private static void afficheResultat(ArrayList<Rubrique> tabRubriqueBilanTotal) {
        
        for (int i = 0; i < tabRubriqueBilanTotal.size(); i++) {
            
            
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_lire;
    private javax.swing.JButton button_parcourir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_fichier;
    private javax.swing.JTextArea text_form;
    // End of variables declaration//GEN-END:variables
}
